$schema: mcp-agent-main/schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console, file]
  level: info
  progress_display: true
  path_settings:
    path_pattern: "logs/tweet-processor-{unique_id}.jsonl"
    unique_id: "timestamp"
    timestamp_format: "%Y%m%d_%H%M%S"

# MCP Servers
mcp:
  servers:
    # Google Drive MCP Server (for reading newsletter articles)
    google_drive:
      command: "python"
      args: ["src/mcp_servers/google_drive_server.py"]
      description: "Access Google Drive documents for newsletter content"

    # Twitter MCP Server (for posting tweets)
    twitter:
      command: "python"
      args: ["src/mcp_servers/twitter_server.py"]
      description: "Post tweets to Twitter/X"

# Anthropic Configuration
# API keys are stored in mcp_agent.secrets.yaml (gitignored)
anthropic:
  default_model: claude-sonnet-4-5-20250929

# OpenAI Configuration (fallback)
openai:
  default_model: "gpt-4o-mini"

